name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version_prefix: ${{ steps.variables.outputs.version_prefix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install xmllint
        run: |
          sudo apt update
          sudo apt install -y libxml2-utils

      - name: Setup variables
        id: variables
        shell: bash
        run: |
          VERSION_PREFIX=$(xmllint --xpath '/*[local-name()="Project"]/*[local-name()="PropertyGroup"]/*[local-name()="ReleaseVersion"]/text()' Directory.Build.props)

          echo "version_prefix=${VERSION_PREFIX%.*}" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build src/TaglibSharp/TaglibSharp.csproj --configuration Release -p:PackageId=${{ github.repository_owner }}.TagLibSharp -p:Version=${{ needs.prepare.outputs.version_prefix }}.${{ github.run_number }} -p:RepositoryUrl="https://github.com/${{ github.repository }}" -p:PackageProjectUrl="https://github.com/${{ github.repository }}"

      - name: List artifacts
        run: ls -lh src/TaglibSharp/bin/Release/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: |
            src/TaglibSharp/bin/Release/*.nupkg
            src/TaglibSharp/bin/Release/*.snupkg
          if-no-files-found: error

  release:
    needs:
      - prepare
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'workflow_dispatch' && github.ref_name == 'main'
    steps:
      - name: Download packages artifacts
        uses: actions/download-artifact@v8
        with:
          name: packages
          path: packages

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: packages/*.nupkg
          artifactErrorsFailBuild: true
          draft: false
          generateReleaseNotes: false
          skipIfReleaseExists: true
          immutableCreate: true
          name: v${{ needs.prepare.outputs.version_prefix }} (build ${{ github.run_number }})
          tag: v${{ needs.prepare.outputs.version_prefix }}.${{ github.run_number }}

  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: github.event_name == 'workflow_dispatch' && github.ref_name == 'main'
    steps:
      - name: Download packages artifacts
        uses: actions/download-artifact@v8
        with:
          name: packages
          path: packages

      - name: Push to GitHub
        run: >-
          dotnet nuget push
          packages/*.TagLibSharp.*.nupkg
          --no-symbols
          --skip-duplicate
          --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Push to NuGet
        run: >-
          dotnet nuget push
          packages/*.TagLibSharp.*.nupkg
          --skip-duplicate
          --source https://api.nuget.org/v3/index.json
          --api-key ${{ secrets.NUGET_API_KEY }}
